name: "Tree"

exports: "mootools-tree.js"

web: "[cpojer.net](http://cpojer.net)"
demo: http://cpojer.net/MooTools/tree/Demos/

description: "A set of components to sort and/or collapse/expand a tree."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Christoph Pojer](http://cpojer.net/)"

author: "cpojer"
authors: "[Christoph Pojer](http://cpojer.net)"
category: Interface
tags: [tree, collapse, cookie, sortable tree, sortable]

sources:
    - "Source/Tree.js"
    - "Source/Collapse.js"
    - "Source/Collapse.Cookie.js"
