var COUNTRY_TERRITORY_JSON = {
    "Abkhazia":"Abkhazia.png",
    "Afghanistan":"Afghanistan.png",
    "Aland":"Aland.png",
    "Albania":"Albania.png",
    "Algeria":"Algeria.png",
    "American Samoa":"American-Samoa.png",
    "Andorra":"Andorra.png",
    "Angola":"Angola.png",
    "Anguilla":"Anguilla.png",
    "Antarctica":"Antarctica.png",
    "Antigua and Barbuda":"Antigua-and-Barbuda.png",
    "Argentina":"Argentina.png",
    "Armenia":"Armenia.png",
    "Aruba":"Aruba.png",
    "Australia":"Australia.png",
    "Austria":"Austria.png",
    "Azerbaijan":"Azerbaijan.png",
    "Bahamas":"Bahamas.png",
    "Bahrain":"Bahrain.png",
    "Bangladesh":"Bangladesh.png",
    "Barbados":"Barbados.png",
    "Belarus":"Belarus.png",
    "Belgium":"Belgium.png",
    "Belize":"Belize.png",
    "Benin":"Benin.png",
    "Bermuda":"Bermuda.png",
    "Bhutan":"Bhutan.png",
    "Bolivia":"Bolivia.png",
    "Bosnia and Herzegovina":"Bosnia-and-Herzegovina.png",
    "Botswana":"Botswana.png",
    "Brazil":"Brazil.png",
    "British Virgin Islands":"British-Virgin-Islands.png",
    "Brunei":"Brunei.png",
    "Bulgaria":"Bulgaria.png",
    "Burkina Faso":"Burkina-Faso.png",
    "Burundi":"Burundi.png",
    "Cambodia":"Cambodia.png",
    "Cameroon":"Cameroon.png",
    "Canada":"Canada.png",
    "Cape Verde":"Cape-Verde.png",
    "Cayman Islands":"Cayman-Islands.png",
    "Central African Republic":"Central-African-Republic.png",
    "Chad":"Chad.png",
    "Chile":"Chile.png",
    "China":"China.png",
    "Colombia":"Colombia.png",
    "Comoros":"Comoros.png",
    "Costa Rica":"Costa-Rica.png",
    "Cote d'Ivoire":"Cote-d'Ivoire.png",
    "Croatia":"Croatia.png",
    "Cuba":"Cuba.png",
    "Cyprus":"Cyprus.png",
    "Czech Republic":"Czech-Republic.png",
    "Democratic Republic of the Congo":"Democratic-Republic-of-the-Congo.png",
    "Denmark":"Denmark.png",
    "Djibouti":"Djibouti.png",
    "Dominica":"Dominica.png",
    "Dominican Republic":"Dominican-Republic.png",
    "East Timor":"East-Timor.png",
    "Ecuador":"Ecuador.png",
    "Egypt":"Egypt.png",
    "El Salvador":"El-Salvador.png",
    "England":"England.png",
    "Equatorial Guinea":"Equatorial-Guinea.png",
    "Eritrea":"Eritrea.png",
    "Estonia":"Estonia.png",
    "Ethiopia":"Ethiopia.png",
    "Falkland Islands":"Falkland-Islands.png",
    "Faroes":"Faroes.png",
    "Fiji":"Fiji.png",
    "Finland":"Finland.png",
    "France":"France.png",
    "Gabon":"Gabon.png",
    "Gambia":"Gambia.png",
    "Georgia":"Georgia.png",
    "Germany":"Germany.png",
    "Ghana":"Ghana.png",
    "Greece":"Greece.png",
    "Greenland":"Greenland.png",
    "Grenada":"Grenada.png",
    "Guam":"Guam.png",
    "Guatemala":"Guatemala.png",
    "Guernsey":"Guernsey.png",
    "Guinea Bissau":"Guinea-Bissau.png",
    "Guinea":"Guinea.png",
    "Guyana":"Guyana.png",
    "Haiti":"Haiti.png",
    "Honduras":"Honduras.png",
    "Hong Kong":"Hong-Kong.png",
    "Hungary":"Hungary.png",
    "Iceland":"Iceland.png",
    "India":"India.png",
    "Indonesia":"Indonesia.png",
    "Iran":"Iran.png",
    "Iraq":"Iraq.png",
    "Ireland":"Ireland.png",
    "Isle of Man":"Isle-of-Man.png",
    "Israel":"Israel.png",
    "Italy":"Italy.png",
    "Jamaica":"Jamaica.png",
    "Japan":"Japan.png",
    "Jersey":"Jersey.png",
    "Jordan":"Jordan.png",
    "Kazakhstan":"Kazakhstan.png",
    "Kenya":"Kenya.png",
    "Kiribati":"Kiribati.png",
    "Kosovo":"Kosovo.png",
    "Kuwait":"Kuwait.png",
    "Kyrgyzstan":"Kyrgyzstan.png",
    "Laos":"Laos.png",
    "Latvia":"Latvia.png",
    "Lebanon":"Lebanon.png",
    "Lesotho":"Lesotho.png",
    "Liberia":"Liberia.png",
    "Libya":"Libya.png",
    "Liechtenstein":"Liechtenstein.png",
    "Lithuania":"Lithuania.png",
    "Luxembourg":"Luxembourg.png",
    "Macau":"Macau.png",
    "Macedonia":"Macedonia.png",
    "Madagascar":"Madagascar.png",
    "Malawi":"Malawi.png",
    "Malaysia":"Malaysia.png",
    "Maldives":"Maldives.png",
    "Mali":"Mali.png",
    "Malta":"Malta.png",
    "Marshall Islands":"Marshall-Islands.png",
    "Mauritania":"Mauritania.png",
    "Mauritius":"Mauritius.png",
    "Mexico":"Mexico.png",
    "Moldova":"Moldova.png",
    "Monaco":"Monaco.png",
    "Mongolia":"Mongolia.png",
    "Montenegro":"Montenegro.png",
    "Montserrat":"Montserrat.png",
    "Morocco":"Morocco.png",
    "Mozambique":"Mozambique.png",
    "Myanmar":"Myanmar.png",
    "Nagorno Karabakh":"Nagorno-Karabakh.png",
    "Namibia":"Namibia.png",
    "Nauru":"Nauru.png",
    "Nepal":"Nepal.png",
    "Netherlands Antilles":"Netherlands-Antilles.png",
    "Netherlands":"Netherlands.png",
    "New Zealand":"New-Zealand.png",
    "Nicaragua":"Nicaragua.png",
    "Niger":"Niger.png",
    "Nigeria":"Nigeria.png",
    "Norfolk Island":"Norfolk-Island.png",
    "North Cyprus":"North-Cyprus.png",
    "North Korea":"North-Korea.png",
    "Northern Mariana Islands":"Northern-Mariana-Islands.png",
    "Norway":"Norway.png",
    "Oman":"Oman.png",
    "Pakistan":"Pakistan.png",
    "Palau":"Palau.png",
    "Palestine":"Palestine.png",
    "Panama":"Panama.png",
    "Papua New Guinea":"Papua-New-Guinea.png",
    "Paraguay":"Paraguay.png",
    "Peru":"Peru.png",
    "Philippines":"Philippines.png",
    "Pitcairn Islands":"Pitcairn-Islands.png",
    "Poland":"Poland.png",
    "Portugal":"Portugal.png",
    "Puerto Rico":"Puerto-Rico.png",
    "Qatar":"Qatar.png",
    "Republic of the Congo":"Republic-of-the-Congo.png",
    "Romania":"Romania.png",
    "Russia":"Russia.png",
    "Rwanda":"Rwanda.png",
    "Saint Barthelemy":"Saint-Barthelemy.png",
    "Saint Helena":"Saint-Helena.png",
    "Saint Kitts and Nevis":"Saint-Kitts-and-Nevis.png",
    "Saint Lucia":"Saint-Lucia.png",
    "Saint Vincent and the Grenadines":"Saint-Vincent-and-the-Grenadines.png",
    "Samoa":"Samoa.png",
    "San Marino":"San-Marino.png",
    "Sao Tome and Principe":"Sao-Tome-and-Principe.png",
    "Saudi Arabia":"Saudi-Arabia.png",
    "Scotland":"Scotland.png",
    "Senegal":"Senegal.png",
    "Serbia":"Serbia.png",
    "Seychelles":"Seychelles.png",
    "Sierra Leone":"Sierra-Leone.png",
    "Singapore":"Singapore.png",
    "Slovakia":"Slovakia.png",
    "Slovenia":"Slovenia.png",
    "Solomon Islands":"Solomon-Islands.png",
    "Somalia":"Somalia.png",
    "Somaliland":"Somaliland.png",
    "South Africa":"South-Africa.png",
    "South Georgia and the South Sandwich Islands":"South-Georgia-and-the-South-Sandwich-Islands.png",
    "South Korea":"South-Korea.png",
    "South Ossetia":"South-Ossetia.png",
    "Spain":"Spain.png",
    "Sri Lanka":"Sri-Lanka.png",
    "Sudan":"Sudan.png",
    "Suriname":"Suriname.png",
    "Swaziland":"Swaziland.png",
    "Sweden":"Sweden.png",
    "Switzerland":"Switzerland.png",
    "Syria":"Syria.png",
    "Taiwan":"Taiwan.png",
    "Tajikistan":"Tajikistan.png",
    "Tanzania":"Tanzania.png",
    "Thailand":"Thailand.png",
    "Togo":"Togo.png",
    "Tonga":"Tonga.png",
    "Trinidad and Tobago":"Trinidad-and-Tobago.png",
    "Tunisia":"Tunisia.png",
    "Turkey":"Turkey.png",
    "Turkmenistan":"Turkmenistan.png",
    "Turks and Caicos Islands":"Turks-and-Caicos-Islands.png",
    "Tuvalu":"Tuvalu.png",
    "Uganda":"Uganda.png",
    "Ukraine":"Ukraine.png",
    "United Arab Emirates":"United-Arab-Emirates.png",
    "United Kindom":"United-Kindom.png",
    "United States":"United-States.png",
    "Uruguay":"Uruguay.png",
    "US Virgin Islands":"US-Virgin-Islands.png",
    "Uzbekistan":"Uzbekistan.png",
    "Vanuatu":"Vanuatu.png",
    "Vatican City":"Vatican-City.png",
    "Venezuela":"Venezuela.png",
    "Vietnam":"Vietnam.png",
    "Wales":"Wales.png",
    "Western Sahara":"Western-Sahara.png",
    "Yemen":"Yemen.png",
    "Zambia":"Zambia.png",
    "Zimbabwe":"Zimbabwe.png"
}


var OTHER = {
    "European Union":"European-Union.png",
    "Commonwealth":"Commonwealth.png",
    "Mars":"Mars.png",
    "Micronesia":"Micronesia.png",
    "NATO":"NATO.png",
    "Olympics":"Olympics.png",
    "Red Cross":"Red-Cross.png",
    "United Nations":"United-Nations.png",
    "World":"World.png"
}